export const SET_USER_DATA = "SET_USER_DATA";
export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const FETCH_FRIENDS_SUCCESS = "FETCH_FRIENDS_SUCCESS";
export const FETCH_PENDING_SUCCESS = "FETCH_PENDING_SUCCESS";
export const FETCH_FRIENDS_START = "FETCH_FRIENDS_START";
export const FETCH_FRIENDS_FAIL = "FETCH_FRIENDS_FAIL";
export const FETCH_SUGGESSTED_FRIEND_SUCCESS = "FETCH_SUGGESSTED_FRIEND_SUCCESS";

export const FETCH_POST_START = "FETCH_POST_START";
export const FETCH_ALLPOST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_ALLPOST_SUCCESS_WITH_CHECKED = "FETCH_ALLPOST_SUCCESS_WITH_CHECKED";
export const FETCH_POST_FAIL = "FETCH_POST_FAIL";
export const FETCH_MY_POST_COUNT_SUCCESS = "FETCH_MY_POST_COUNT_SUCCESS";
export const MAKE_LIKE_SUCCESS = "MAKE_LIKE_SUCCESS";
export const MAKE_DISLIKE_SUCCESS = "MAKE_DISLIKE_SUCCESS";
export const CLEAR_POST_DATA = "CLEAR_POST_DATA";
export const SET_POSTDATA_LENGTH_TO_ZERO = "SET_POSTDATA_LENGTH_TO_ZERO"
export const SET_CHECKBOX_CHECKED = "SET_CHECKBOX_CHECKED"
